apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#helmGlobals:
#  chartHome: ../../charts # To test locally
helmCharts:
  - name: jellyfin
    releaseName: jellyfin
    version: 1.5.0
    repo: https://piwero.github.io/helmseum
    valuesFile: values.yaml
