apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#helmGlobals:
#  chartHome: ../../charts
helmCharts:
  - name: jellyfin
    releaseName: jellyfin
    version: 2.0.19
    repo: "https://raw.githubusercontent.com/Piwero/helmseum/gh-pages"
    valuesFile: values.yaml
