apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mediaserver

helmGlobals:
  chartHome: ../../charts # To test locally
helmCharts:
  - name: mediaserver
    releaseName: mediaserver
    version: 1.3.1
#    repo: https://piwero.github.io/helmseum
    valuesFile: values.yaml

secretGenerator:
  - name: secret-docker
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=dockerconfig.json # TBC
  - name: openvpn-user-secret
    literals:
      - OPENVPN_USER={{YOUR_MULLVAD_USER}}
configMapGenerator:
  - name: mediaserver-env-values
    literals:
      - TZ="Europe/London"
      - PUID="1000"
      - PGID="1000"
      - VPN_SERVICE_PROVIDER="mullvad"
      - VPN_TYPE="openvpn"
      - SERVER_CITIES="amsterdam"
      - UMASK_SET="022"
      - WEBUI_PORT="8080"
      - LOG_LEVEL="debug"

generatorOptions:
  disableNameSuffixHash: true
