apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mediaserver

helmGlobals:
  chartHome: ../../charts # To test locally
helmCharts:
  - name: mediaserver
    releaseName: mediaserver
    # version: 1.4.0
    # repo: https://piwero.github.io/helmseum
    valuesFile: values.yaml

secretGenerator:
  - name: secret-docker
    type: kubernetes.io/dockerconfigjson
    files:
      - .dockerconfigjson=dockerconfig.json
  - name: wireguard-secrets
    literals:
      - WIREGUARD_PRIVATE_KEY=""
      - WIREGUARD_PRESHARED_KEY=""
configMapGenerator:
  - name: mediaserver-env-values
    literals:
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - VPN_INTERFACE=eth0
      - FIREWALL="off"
      - DOT="off"
      - WIREGUARD_ADDRESSES=10.141.231.118/32
      - SERVER_COUNTRIES=Netherlands

generatorOptions:
  disableNameSuffixHash: true
