{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mediaserver.labels" . | nindent 4 }}
data:
    TZ: "Europe/London"
    PUID: "1000"
    PGID: "1000"
    VPN_SERVICE_PROVIDER: "${VPN_SERVICE_PROVIDER}"
    VPN_TYPE: "${VPN_TYPE}"
    SERVER_CITIES: "${SERVER_CITIES}"
    UMASK_SET: "022"
    WEBUI_PORT: "8080"
{{- end }}