{{- range .Values.ingressRoutes }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
  labels:
    {{- include "mediaserver.labels" $ | nindent 4 }}
  annotations:
    {{- with .annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  entryPoints:
    {{- range .entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    - match: Host(`{{ .host }}`)
      kind: Rule
      {{- if .middlewares }}
      middlewares:
        {{- range .middlewares }}
        - name: {{ .name }}
        {{- end }}
      {{- else }}
      middlewares: []
      {{- end }}
      services:
        - kind: Service
          name: {{ .serviceName }}
          namespace: {{ $.Values.namespace }}
          port: {{ .servicePort | default 80 }}
  {{- if .tls }}
  tls:
    {{- toYaml .tls | nindent 4 }}
  {{- end }}
---
{{- end }}