{{- range .Values.pvs }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  storageClassName: {{ .storageClassName }}
  capacity:
    storage: {{ .capacity }}
  accessModes:
    - {{ .accessModes }}
  persistentVolumeReclaimPolicy: {{ .persistentVolumeReclaimPolicy }}
  nfs:
    path: {{ .nfsPath }}
    server: {{ .nfsServer }}
    readOnly: {{ .readOnly }}
---
{{- end }}