name: Lint Helm Charts
on:
  push:
    branches:
      - main
    paths:
      - "charts/**"
jobs:
  lint-helm-charts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.12.1
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          check-latest: true

      - name: Add repositories
        run: |
          for dir in $(ls -d charts/*/); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done

      - name: Run Helm lint
        id: lint-helm
        run: |
          for dir in charts/*; do
            helm lint $dir
          done