name: Release Charts

on:
  workflow_run:
    workflows: [ Lint Helm Charts ]
    branches: [ main ]
    types:
      - completed
jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token

    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Load secrets from 1pass
        uses: 1password/load-secrets-action@v2
        with:
          # Export loaded secrets as environment variables
          export-env: true
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          REPOSITORY_OWNER: "op://Homelab/Github Actions -Helmseum/username"
          GITHUB_REPOSITORY: "op://Homelab/Github Actions -Helmseum/repo"

      - name: Print masked secret
        run: |
          echo "REPOSITORY_OWNER: $REPOSITORY_OWNER"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v43
        with:
          dir_names_max_depth: 2
          dir_names_exclude_current_dir: "true"
          dir_names: "true"
          files: "charts/**/*"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: engineerd/configurator@v0.0.10
        with:
          name: "helm-docs"
          url: "https://github.com/norwoodj/helm-docs/releases/download/v1.11.0/helm-docs_1.11.0_Linux_x86_64.tar.gz"
          pathInArchive: "helm-docs"

      - uses: engineerd/configurator@v0.0.10
        with:
          name: "cr"
          url: "https://github.com/helm/chart-releaser/releases/download/v1.6.0/chart-releaser_1.6.0_linux_amd64.tar.gz"
          pathInArchive: "cr"

      - name: Add repositories
        run: |
          for dir in $(ls -d charts/*/); do
            helm dependency list $dir 2> /dev/null | tail +2 | head -n -1 | awk '{ print "helm repo add " $1 " " $3 }' | while read cmd; do $cmd; done
          done

      - name: Bump version
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          npm install ci
          mkdir .cr-release-packages
          for dir in ${ALL_CHANGED_FILES}; do
            pushd "$dir";

            cp -f ../../.github/configs/cr.yaml ./
            cp -f ../../.releaserc.js ./
            ln -s ../../.cr-release-packages

            export CHART_NAME=$(basename $(pwd))
            npx semantic-release;

            popd;
          done
          
          echo "CR Index"
          echo "REPOSITORY_OWNER: $REPOSITORY_OWNER"
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          [ "$(ls -A .cr-release-packages)" ] && cr index -o "$(REPOSITORY_OWNER)" -r "$(GITHUB_REPOSITORY)" --push --packages-with-index --index-path .
